<template>
  <div class="supplier_orders_page"><header><h1>Orders</h1><p>Track customer orders and update their status.</p></header>
  <div v-if="error" class="message error">{{ error }}</div><div v-if="loading" class="state">Loading orders…</div>
  <section v-else class="card"><div class="controls"><input v-model.trim="search" type="search" placeholder="Search order, buyer or product…" aria-label="Search orders"><select v-model="statusFilter"><option value="All">All statuses</option><option v-for="s in statuses" :key="s">{{ s }}</option></select></div>
  <div v-if="filtered.length===0" class="state">No orders match your filters.</div><div v-else class="table-wrap"><table><thead><tr><th>Order</th><th>Buyer</th><th>Items</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>
  <tr v-for="order in filtered" :key="order.id"><td><strong>{{ order.id }}</strong></td><td>{{ order.buyer }}</td><td>{{ order.items || "—" }}</td><td>{{ order.date }}</td><td>{{ formatPrice(order.total) }}</td><td><select :value="order.status" :disabled="updatingId===order.id" @change="changeStatus(order,$event.target.value)"><option v-for="s in statuses" :key="s">{{ s }}</option></select></td></tr>
  </tbody></table></div></section></div>
</template>
<script setup>
import { computed,ref } from "vue";import {useSupplierData} from "@/data/supplierData";
const {orders,loading,updateOrderStatus}=useSupplierData();const search=ref("");const statusFilter=ref("All");const updatingId=ref(null);const error=ref("");const statuses=["Pending","Processing","Ready to ship","Out for delivery","Delivered","Cancelled"];
const filtered=computed(()=>orders.value.filter(o=>{const q=search.value.toLowerCase();return(!q||[o.id,o.buyer,o.items].filter(Boolean).join(" ").toLowerCase().includes(q))&&(statusFilter.value==="All"||o.status===statusFilter.value)}));
const formatPrice=v=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:2}).format(Number(v||0));
async function changeStatus(order,status){updatingId.value=order.id;error.value="";try{await updateOrderStatus(order.id,status)}catch(e){error.value=e.message||"Unable to update order status."}finally{updatingId.value=null}}
</script>
<style scoped>.supplier_orders_page{min-height:100vh;padding:30px;max-width:1280px;margin:auto;background:#f7f5f2;color:#4d3933}.supplier_orders_page header{margin-bottom:20px}.supplier_orders_page h1{margin:0;font:700 30px Georgia,serif}.supplier_orders_page p{color:#85736d}.card{background:#fff;border:1px solid #e5dfda;border-radius:13px;overflow:hidden}.controls{display:flex;gap:10px;padding:16px;border-bottom:1px solid #eeeae7}.controls input,.controls select,td select{padding:9px 11px;border:1px solid #e4ddd8;border-radius:7px;background:#fff;color:#4d3933}.controls input{flex:1}.table-wrap{overflow:auto}table{width:100%;min-width:850px;border-collapse:collapse}th,td{padding:13px 16px;border-bottom:1px solid #f0ece9;text-align:left;font-size:13px}th{font-size:11px;color:#9b8a82}.state{padding:35px;text-align:center;color:#8e7d75}.message{margin-bottom:14px;padding:11px;border-radius:7px}.error{background:#fae5e1;color:#a8473d}@media(max-width:600px){.supplier_orders_page{padding:18px 14px}.controls{flex-direction:column}}</style>